services:
  - type: web
    name: biterush
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    build:
      docker:
        targetPlatform: linux/amd64
    envVars:
      - key: APP_ENV
        value: production
